### ISSUE TITLE
デスク

### ISSUE THREAD

**Issue by cobachie** [shiolab/general#1]
mimosaでつかっているデスクがちょっとせまいので、
SIPに移動するタイミングで新しいデスクがほしいです。

1台3万以内くらいの想定で調べてみました。
こんな感じはどうでしょう？

* [Ceha プレノ 平机 引出し付き オーク 幅1400×奥行700×高さ720mm 1台（4梱包）](http://www.askul.co.jp/p/2842827/)
* [【日本製】スチールデスクSH オフィスデスク 事務机 片袖机 幅1400×奥行700×高さ700mm OC-SH147K](http://www.office-com.jp/products/detail.php?product_id=185332) メープル/ホワイト
* [L字型 パソコンデスク コンパクト 収納 引き出し付き 幅145cm ホワイト×オーク](https://www.amazon.co.jp/dp/B00O1TMBYE?psc=1)
* [IKEA ALEX](http://www.ikea.com/jp/ja/catalog/products/60260716/)

脚がブラックならこっち
* [Ceha プレノヴィーボデスクシステム 平机 引出し付き ナチュラル／ブラック 幅1400×奥行600×高さ720mm 1台（3梱包）](http://www.askul.co.jp/p/1632469/)
* [IKEA BEKANT デスク, バーチ材突き板, ブラック](http://www.ikea.com/jp/ja/catalog/products/S99022791/)

**Comment by cobachie** [comment]
考えた結果、Ceha プレノ がいいです。（幅120cm）
[Ceha プレノ 平机 引出し付き オーク 幅1200×奥行700×高さ720mm 1台（4梱包）](http://www.askul.co.jp/p/2842809/)

**Comment by ozamasa** [comment]
12月2日

**Comment by ozamasa** [comment]
きた。なんとなく組み立てた。あと配置。

**Comment by cobachie** [comment]
ありがとうございまーす！！
