### ISSUE TITLE
入居企業得意業務一覧＆SIPホームページ

### ISSUE THREAD

**Issue by cobachie** [shiolab/general#16]

**Comment by ozamasa** [comment]
1. 入居企業得意業務一覧について
   106号室の欄へ各項目をご記入の上、データを返送ください。
2. SIPのホームページについて
   SIPホームぺージにある「入居企業」ページへロゴ、TEL・FAX、住所を記載します。
   掲載可能なロゴのデータ及び、挨拶文のご準備をお願いいたします。

**Comment by ozamasa** [comment]
出しました

**Comment by cobachie** [comment]
🙇
