### ISSUE TITLE
本棚

### ISSUE THREAD

**Issue by cobachie** [shiolab/general#2]
mimosaでつかってる本棚を持っていけなかったら、あたらしい本棚が必要。

* [KALLAX シェルフユニット, バーチ調](http://www.ikea.com/jp/ja/catalog/products/60275869/#/60275869)

**Comment by ozamasa** [comment]
あとこれ。

- [BUMERANGハンガー, ナチュラル](http://www.ikea.com/jp/ja/catalog/products/30238538/)

- [MULIG洋服ラック, ホワイト](http://www.ikea.com/jp/ja/catalog/products/80179433/)

**Comment by ozamasa** [comment]
12月7日

**Comment by cobachie** [comment]
これも追加でお願いします！
ゴミ箱
http://www.askul.co.jp/v/81740/?cateId=2&andOr=&itemExpl=&searchWord=&categoryS=&categoryM=0712006&categoryL=0712&categoryLl=07&categoryLll=&deliveryEstimate=0&minPriceRange=&maxPriceRange=&sortDir=0&itemGroupCd=81740&pubPage=&ctg=&ctgItemCd=&cutTermEndDate=&printerMaker=&printerType=&printerModel=&refineKbn=&refineCD1=&refineCD2=&refineCD3=&variationItemLImgPath=L1%2F8215397_l1.jpg&supplierCd=&supplierSubCd=&grpSpec1=0141_011300_W%E3%83%9B%E3%83%AF%E3%82%A4%E3%83%88&lstSelSpecCd=0141

**Comment by ozamasa** [comment]
これはいったんクローズ
