### ISSUE TITLE
ミーティングスペースのテーブル、チェア

### ISSUE THREAD

**Issue by cobachie** [shiolab/general#4]
ミーティングスペースのテーブルと、チェア（4脚くらい？）がほしい。

**Comment by ozamasa** [comment]
大工に「技術もアイデアもあるけど、時間がない」と言われてしまったので、どっかで買う。

**Comment by cobachie** [comment]
- [無印 折りたたみテーブル・幅１６０ｃｍ・オーク材　幅１６０×奥行７０×高さ７２ｃｍ](http://www.muji.net/store/cmdty/detail/4549738369448?searchno=2)
- [無印 無垢材テーブル・オーク材・幅１８０ｃｍ　幅１８０×奥行８０×高さ７２ｃｍ](http://www.muji.net/store/cmdty/detail/4547315892402?searchno=5)
- [IKEA BEKANT 会議用テーブル, バーチ材突き板, ホワイト](http://www.ikea.com/jp/ja/catalog/products/S39006280/#/S29006266) ※脚がブラックもあり

チェア
- [IKEA ÖRFJÄLL / SPORREN 回転チェア, ホワイト, ヴィースレ ライトグレー](http://www.ikea.com/jp/ja/catalog/products/S99162442/)

**Comment by cobachie** [comment]
チェア
http://item.rakuten.co.jp/dondon/k-016w/
ホワイトサンド（脚: ナチュラル）
がいいなあ

**Comment by ozamasa** [comment]
椅子は12月5日
テーブルは12月7日

**Comment by ozamasa** [comment]
きたのでクローズ
