### ISSUE TITLE
冷蔵庫

### ISSUE THREAD

**Issue by cobachie** [shiolab/general#5]
小さくていいのであるとうれしい。

* [ハイアール 85L 2ドア冷蔵庫（直冷式）ホワイト【右開き】Haier JR-N85A-W](https://www.amazon.co.jp/Haier-%E3%83%8F%E3%82%A4%E3%82%A2%E3%83%BC%E3%83%AB-JR-N85A-2%E3%83%89%E3%82%A2%E5%86%B7%E8%94%B5%E5%BA%AB%EF%BC%88%E7%9B%B4%E5%86%B7%E5%BC%8F%EF%BC%89%E3%83%9B%E3%83%AF%E3%82%A4%E3%83%88%E3%80%90%E5%8F%B3%E9%96%8B%E3%81%8D%E3%80%91Haier-JR-N85A-W/dp/B00WQQPRRC/ref=sr_1_2?s=appliances&ie=UTF8&qid=1478573721&sr=1-2&keywords=%E5%86%B7%E8%94%B5%E5%BA%AB)

**Comment by ozamasa** [comment]
これにしたの閉じます
https://www.irisohyama.co.jp/kitchen/reizouko/irr-90tf.html
