### ISSUE TITLE
ホワイトボード

### ISSUE THREAD

**Issue by cobachie** [shiolab/general#6]
脚付きの可動式のやつ（ふつうのやつ）があるといいのでは。

**Comment by cobachie** [comment]
これがかわいい
[コマイ 天然木枠ホワイトボード（両面タイプ）スチール 幅1525mm イレーザー･マーカー（黒・赤）･マグネット式粉受け付 1台（2梱包）](http://www.askul.co.jp/p/1612770/)

**Comment by ozamasa** [comment]
12月2日
