### ISSUE TITLE
名刺

### ISSUE THREAD

**Issue by cobachie** [shiolab/general#7]
住所がかわるので、名刺をつくりなおす

**Comment by ozamasa** [comment]
いまのより、もう少し薄いやつがいいです。

**Comment by cobachie** [comment]
Kami Lab.に行ってきました。
今より薄くて、表面がちょっとポコポコしてる紙にしました。
色は、いまと大体同じオフホワイトです。

明日11/18に発注したとして、
刷り上がるのは12月9日(金) or 12(月)あたりになるそうです。
